/* eslint-disable @next/next/no-img-element */
// eslint-disable-next-line @next/next/no-img-element

import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

import React, { useState, useEffect } from "react";

export async function getStaticProps() {
  const resp = await fetch(
    "https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json"
  );

  return {
    props: {
      pokemon: await resp.json(),
    },
  };
}

export default function Home({ pokemon }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.grid}>
        {pokemon.map((pok) => (
          <div className={styles.card} key={pok.id}>
            <Link href={`/pokemon/${pok.id}`}>
              <a>
                <img
                  src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${pok.image}`}
                  alt={pok.name}
                />
              </a>
            </Link>
            <h5>{pok.name}</h5>
          </div>
        ))}
      </div>
    </div>
  );
}
